### ISSUE TITLE
Collect stethoscope files in folders

### ISSUE THREAD

**Issue by ghost** [MonetDBSolutions/monetdb-stethoscope#21]
Pystethoscope will produce  a potential large trace. On a production system it may easy amount to 100MB/min of JSON data.
Since inspection is typically an 'afterthought', we need to limit the amount of data for post-analysis.

Proposal: add the following options:
--logs, to designate a directory where to keep the JSON log files
--interval, to designate the minutes between switching JSON files
--retention, to designate how long the log is kept

The interval preferably is a divisor of the hour.
The logfiles are named as DBNAME_interval-date-time.json.gz

As an intermediate step, this functionality can also be cast in a small StethoscopePool.py program

**Comment by lrpereira** [comment]
Minimal events reduces the output by 50%. If needed will comeback to this.
